apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sqlserver-data
  namespace: financeiro
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 256Gi
